name: Deploy to DO

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.DO_HOST }}
          username: root
          key: ${{ secrets.DO_SSH_KEY }}
          port: 22
          script_stop: true
          script: |
            echo "🚀 Iniciando deploy..."

            # Ir al proyecto
            cd /var/www/misionforasteros || exit 1

            # Actualizar repo
            git pull origin main

            # Levantar contenedores sin tumbarlos
            docker compose up -d --build

            echo "✅ Deploy completado"